; Hi there!
; This code was generated by PySembler, made by Henrysjm#1827.
[BITS 16]
[ORG 7c0h]

MOV AH, 0
MOV AL, 12H
INT 10H
mov si, reservedloaddata
call blue
call printString
mov si, DataChunkA
call grey
call printString
mov si, DataChunkB
call red
call printString
mov si, DataChunkC
call green
call printString
mov si, DataChunkD
call blue
call printString
mov si, DataChunkE
call grey
call printString
JMP $

printString:
printChar:
mov ah, 09h
mov bh, 0  
mov cx, 1
lodsb
cmp al, 0x00
je done     
int 10h   
mov bh, 0
mov ah, 03h
int 10h
mov ah, 02h
mov bh, 0
inc dl
int 10h
jmp printChar
done: 
mov ah, 02h
mov bh, 0
mov dl, 0
inc dh  
int 10h
ret        

blue:
mov bl, 0011b
ret 

red:
mov bl, 0x000C
ret

green:
mov bl, 0x000A
ret

grey:
mov bl, 0x0007
ret 
DataChunka: db 'Welcome to a cool little demo!',10,13,0
DataChunkb: db 'Red',10,13,0
DataChunkc: db 'Green',10,13,0
DataChunkd: db 'Blue',10,13,0
DataChunke: db 'Grey',10,13,0
reservedloaddata: db 'Loaded!',10,13,0

TIMES 510-($-$$) db 0
dw 0xAA55
